// Generated by CoffeeScript 1.6.1
(function() {
  var SampleApp, app,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SampleApp = (function(_super) {

    __extends(SampleApp, _super);

    function SampleApp() {
      SampleApp.__super__.constructor.apply(this, arguments);
      this.x = this.width / 2;
      this.y = this.height / 2;
      this.speed = 10;
    }

    SampleApp.prototype.update = function(dt) {
      return this.radius = Math.abs(this.mouse.x - this.mouse.px) + Math.abs(this.mouse.y - this.mouse.py);
    };

    SampleApp.prototype.draw = function() {
      this.ctx.beginPath();
      this.ctx.arc(this.mouse.x || this.width / 2, this.mouse.y || this.height / 2, this.radius * 1.4, 0, 2 * Math.PI, false);
      this.ctx.fillStyle = '#000';
      this.ctx.fill();
      this.ctx.strokeStyle = '#fff';
      this.ctx.stroke();
      this.ctx.closePath();
      this.ctx.beginPath();
      this.ctx.arc(this.mouse.x || this.width / 2, this.mouse.y || this.height / 2, this.radius, 0, 2 * Math.PI, false);
      this.ctx.fillStyle = '#fff';
      this.ctx.fill();
      return this.ctx.closePath();
    };

    return SampleApp;

  })(Splash.App);

  app = new SampleApp('canvas', document.width, document.height);

  app.run();

}).call(this);
