// Generated by CoffeeScript 1.6.1
(function() {
  var Particle, ParticleSystem, SampleApp, app, randomFloat,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  randomFloat = function(min, max) {
    return min + Math.random() * (max - min);
  };

  ParticleSystem = (function() {

    function ParticleSystem() {
      this.particles = [];
    }

    ParticleSystem.prototype.create = function(x, y, color) {
      var angle, particle, speed, vx, vy, _i, _ref, _results;
      _results = [];
      for (angle = _i = 0, _ref = Math.round(360 / 10); _i < 360; angle = _i += _ref) {
        speed = randomFloat(60.0, 200.0);
        vx = speed * Math.cos(angle * Math.PI / 180);
        vy = speed * Math.sin(angle * Math.PI / 180);
        particle = new Particle(x, y, vx, vy, color);
        _results.push(this.particles.push(particle));
      }
      return _results;
    };

    ParticleSystem.prototype.update = function(dt) {
      var p, _i, _len, _ref;
      _ref = this.particles;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        p = _ref[_i];
        p.update(dt);
      }
      return this.particles = this.particles.filter(function(p) {
        return p.scale > 0;
      });
    };

    ParticleSystem.prototype.draw = function(ctx) {
      var p, _i, _len, _ref, _results;
      _ref = this.particles;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        p = _ref[_i];
        _results.push(p.draw(ctx));
      }
      return _results;
    };

    return ParticleSystem;

  })();

  Particle = (function() {

    function Particle(x, y, vx, vy, color) {
      var maxScaleSpeed, maxSize, minScaleSpeed, minSize;
      this.x = x;
      this.y = y;
      this.vx = vx;
      this.vy = vy;
      this.color = color;
      minSize = 10;
      maxSize = 30;
      minScaleSpeed = 1.0;
      maxScaleSpeed = 4.0;
      this.scale = 1.0;
      this.radius = randomFloat(minSize, maxSize);
      this.scaleSpeed = randomFloat(minScaleSpeed, maxScaleSpeed);
    }

    Particle.prototype.update = function(dt) {
      this.scale -= this.scaleSpeed * dt;
      if (this.scale <= 0) {
        this.scale = 0;
      }
      this.x += this.vx * dt;
      return this.y += this.vy * dt;
    };

    Particle.prototype.draw = function(ctx) {
      ctx.beginPath();
      ctx.arc(this.x, this.y, this.radius * this.scale, 0, 2 * Math.PI, true);
      ctx.closePath();
      ctx.fillStyle = this.color;
      return ctx.fill();
    };

    return Particle;

  })();

  SampleApp = (function(_super) {

    __extends(SampleApp, _super);

    function SampleApp() {
      SampleApp.__super__.constructor.apply(this, arguments);
      this.particleSystem = new ParticleSystem;
    }

    SampleApp.prototype.update = function(dt) {
      if (this.mouse.pressed.left) {
        this.particleSystem.create(this.mouse.x, this.mouse.y, "#FFA318");
        this.particleSystem.create(this.mouse.x, this.mouse.y, "#525252");
      }
      return this.particleSystem.update(dt);
    };

    SampleApp.prototype.draw = function() {
      this.ctx.clearRect(0, 0, this.width, this.height);
      return this.particleSystem.draw(this.ctx);
    };

    return SampleApp;

  })(Splash.App);

  app = new SampleApp('canvas', 800, 600);

  window.onblur = function() {
    return app.stop();
  };

  window.onfocus = function() {
    return app.run();
  };

  app.run();

}).call(this);
